const {initMockedMongoDB, resetMockedMongoDB, closeMockedMongoDB} = require('../support/mongodb-mocking');

const userService = require('../../../src/services/user-service');
const User = require("../../../src/models/User");
const crypto = require("crypto");
const Credentials = require("../../../src/models/Credentials");
const {copyObject} = require("../support/copyObject");
const {ObjectId} = require("mongo-mock");

const demouser = new User('testuser', 'John', 'Doe', 'jd@test.com', 'secret', false);
const demouser2 = new User('testuser2', 'Jane', 'Doe', 'jad@test.com', 'xyz', false);

let db;

describe('auth-service unit-tests', function (){
    beforeAll(async function (){
        db = await initMockedMongoDB();
    });
    afterEach(function (){
        resetMockedMongoDB(db);
    });
    afterAll(function (){
        closeMockedMongoDB(db);
    });

    describe('user creation tests', function (){
        it('insert user to db', async function (){
            await userService.add(db, copyObject(demouser));
            const expected = copyObject(demouser);
            expected._id = expect.any(ObjectId);        // accept any ObjectId as the _id is randomly generated by the database
            expected.password = expect.any(String);     // accept any string as password is hashed by the backend
            await expect(db.collection('users').findOne()).resolves.toEqual(expected);
        });

        it('expect correct objectId to be returned', async function (){
            const oid = await userService.add(db, copyObject(demouser));
            await expect(db.collection('users').findOne()).resolves.toHaveProperty('_id', oid);
        });

        it('create matching hash of user\'s password', async function (){
            await userService.add(db, copyObject(demouser)); //simple deep-copy using json
            const insertedUser = await db.collection('users').findOne();

            let hash = crypto.createHmac('sha3-256', 'integrationArchitectures');
            hash.update(demouser.password);

            expect(insertedUser).toHaveProperty('password', hash.digest('base64'));
        });
    });

    describe('user lookup tests', function (){
        it('expect correct user to be found', async function (){
            await db.collection('users').insert([demouser, demouser2]);
            const expected = copyObject(demouser);
            expected._id = expect.any(ObjectId);        // accept any ObjectId as the _id is randomly generated by the database
            await expect(userService.get(db, demouser.username)).resolves.toEqual(expected);
        });

        it('expect null when user not found', async function (){
            await expect(userService.get(db, 'username')).resolves.toBe(null);
        });
    });

    describe('user deletion tests', function (){
        it('expect correct user to be deleted', async function (){
            await db.collection('users').insert([demouser, demouser2]);
            await userService.remove(db, demouser.username);
            const actual = db.collection('users').find().toArray();

            await expect(actual).resolves.toHaveLength(1);

            const expected = copyObject(demouser2);     // remaining user should be demouser2
            expected._id = expect.any(ObjectId);        // accept any ObjectId as the _id is randomly generated by the database
            expected.password = expect.any(String);     // accept any string as password is hashed by the backend
            await expect(actual).resolves.toEqual([expected], '');
        });

        it('expect error if the user to be deleted does not exist', async function (){
            await expect(userService.remove(db, demouser.username)).rejects.toThrow(Error);
        });
    });

    describe('credential verification test', function (){
        it('expect user to be returned if credentials match', async function (){
            const demouser_copy = copyObject(demouser);

            let hash = crypto.createHmac('sha3-256', 'integrationArchitectures');
            hash.update(demouser.password);
            demouser_copy.password = hash.digest('base64');

            await db.collection('users').insertOne(demouser_copy);

            const expected = copyObject(demouser);
            expected._id = expect.any(ObjectId);        // accept any ObjectId as the _id is randomly generated by the database
            expected.password = expect.any(String);     // accept any string as password is hashed by the backend

            await expect(userService.verify(db, new Credentials(demouser.username, demouser.password))).resolves.toEqual(expected);
        });

        it('expect error to be thrown if user does not exist', async function (){
            await expect(userService.verify(db, new Credentials(demouser.username, demouser.password))).rejects.toThrow(Error);
        });

        it('expect error to be thrown if password does not match', async function (){
            await db.collection('users').insertOne(demouser);
            await expect(userService.verify(db, new Credentials(demouser.username, demouser.password+'abc'))).rejects.toThrow(Error);
        });
    });
});
